languageCode = "es"
languageName = "Español"
weight = 1
title = "Universo 25"

[params]
  displayName = "Español"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blog-logo.png"
  description = "Un blog del futuro..."

[params.author]
  name = "Universo 25"
  email = "nuno@n9o.xyz"
  image = "img/blog-logo.png"
  headline = "Un blog del futuro..."
  bio = "Un blog del futuro..."
  links = [
    { linkedin = "https://www.linkedin.com/in/emilianosalvatori/" },
    { github = "https://github.com/SonidoCristalino" },
    { telegram = "https://t.me/ThereIsLifeOutThere" },
  ]

[taxonomies]
  tag = "etiquetas"
  category = "categorias"
  author = "autores"
  series = "series"